apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: locations
  name: locations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locations
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: locations
    spec:
      containers:
      - image: locations:0.0.1-SNAPSHOT
        name: locations
        resources: {}
        env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: mariadb-config
                  key: MARIADB_DATABASE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_PASSWORD
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: locations
  name: locations
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: locations
  type: ClusterIP
status:
  loadBalancer: {}
